version: "3.8"
services:
  mongo_db:
    container_name: waste_expert_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    networks:
      - database-network

  api:
    build: .
    container_name: waste_expert_c
    ports:
      - "4000:4000"
    volumes:
      - .:/src
      - /src/node_modules
    depends_on:
      - mongo_db
    networks:
      - database-network
    environment:
      - LOCAL_MONGO_URL=mongodb://root:rootpassword@mongo_db:27017

networks:
  database-network:
    name: database-network
